name: Test
description: Testing

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  color_dark: "#171725"
  image_dark: assets/splash_dark.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true